{% set name = "fitstools" %}
{% set version = "2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://www.usm.uni-muenchen.de/people/cag/{{ name }}-{{ version }}.tar.gz
  sha256: 091c22dcb2445141727fe26f06a7d4ac767bd3a839d92fb277df31dbf976761e

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - automake
  host:
    - ltl
    - libjpeg-turbo

about:
  home: https://www.usm.uni-muenchen.de/people/cag/fitstools.html
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: 'Basic shell commandline programs that can perform many operations on FITS files'

extra:
  recipe-maintainers:
    - drbixx
    - teake
